"""
🔍 GUIDE DE DIAGNOSTIC DES COMMANDES
===================================

Instructions pour identifier pourquoi les commandes ne répondent pas.
"""

def diagnostic_steps():
    print("🔍 DIAGNOSTIC DES COMMANDES QUI NE RÉPONDENT PAS")
    print("=" * 50)
    print()
    print("✅ Étapes de diagnostic :")
    print()
    print("1️⃣ **Vérifiez que le bot est démarré** :")
    print("   - Le bot doit afficher 'El Professor Gnougous est connecté et prêt!'")
    print("   - '10 commandes slash synchronisées' doit apparaître")
    print()
    print("2️⃣ **Testez une commande sur Discord** :")
    print("   - Allez sur votre serveur Discord")
    print("   - Tapez '/' dans un canal")
    print("   - Sélectionnez une commande du bot (ex: /niveau)")
    print("   - Envoyez la commande")
    print()
    print("3️⃣ **Observez les logs en temps réel** :")
    print("   - Regardez la fenêtre du terminal où le bot tourne")
    print("   - Des messages devraient apparaître quand vous utilisez une commande")
    print("   - Cherchez les erreurs ou messages d'interaction")
    print()
    print("4️⃣ **Commandes à tester** :")
    print("   /niveau - Affiche votre profil XP")
    print("   /classement - Top des utilisateurs")
    print("   /boutique - Voir les articles")
    print("   /daily - Bonus quotidien")
    print()
    print("5️⃣ **Signes de problème** :")
    print("   ❌ Discord affiche 'L'application n'a pas répondu'")
    print("   ❌ Aucun log d'interaction dans le terminal")
    print("   ❌ Messages d'erreur dans les logs")
    print()
    print("6️⃣ **Solutions communes** :")
    print("   🔧 Redémarrer le bot")
    print("   🔧 Vérifier les permissions du bot")
    print("   🔧 Attendre quelques minutes")
    print("   🔧 Redémarrer Discord")
    print()
    
def check_common_issues():
    print("🛠️ PROBLÈMES COURANTS ET SOLUTIONS")
    print("=" * 40)
    print()
    print("❌ **'L'application n'a pas répondu'** :")
    print("   → Le bot a un problème de code ou de base de données")
    print("   → Regardez les logs pour voir l'erreur exacte")
    print()
    print("❌ **Commandes visibles mais rien ne se passe** :")
    print("   → Erreur silencieuse dans le code")
    print("   → Problème de permissions")
    print("   → Bot pas correctement configuré")
    print()
    print("❌ **Bot hors ligne** :")
    print("   → Vérifiez que le script Python tourne")
    print("   → Token Discord invalide")
    print("   → Problème de connexion")
    print()
    print("✅ **Le bot répond maintenant avec des logs d'erreur** :")
    print("   → J'ai ajouté des gestionnaires d'erreur")
    print("   → Les erreurs seront maintenant visibles")
    print("   → Utilisez une commande et regardez les logs")
    print()

if __name__ == "__main__":
    diagnostic_steps()
    print()
    check_common_issues()
    print()
    print("🚀 **PROCHAINES ÉTAPES** :")
    print("1. Utilisez une commande sur Discord")
    print("2. Regardez les logs du bot")
    print("3. Reportez-moi toute erreur qui apparaît")
    print()
    input("Appuyez sur Entrée quand vous avez testé une commande...")
